In [84]:
#Question1. Find mean
import numpy as np
import math
a=np.random.random((10,1))
print(a)

[[0.99073152]
 [0.38529122]
 [0.95069761]
 [0.37335117]
 [0.54804633]
 [0.06465154]
 [0.43498341]
 [0.56936532]
 [0.89047847]
 [0.15830329]]


In [85]:
a.mean(axis=0)

array([0.53658999])

In [86]:
#Question2. Find standard deviation and variance
b=np.random.random((20,1))
print(b)

[[0.0460593 ]
 [0.35646717]
 [0.76312332]
 [0.07072049]
 [0.10364731]
 [0.09466335]
 [0.92577819]
 [0.16128664]
 [0.79317098]
 [0.31787109]
 [0.25046508]
 [0.58474629]
 [0.74730268]
 [0.6087912 ]
 [0.93791933]
 [0.04862002]
 [0.94603514]
 [0.16043035]
 [0.75304936]
 [0.576311  ]]


In [87]:
#variance
b.var(axis=0)

array([0.10551939])

In [88]:
#standard deviation
b.std(axis=0)

array([0.32483748])

In [89]:
#Question3.#Q3.Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random.
#Print the matrix which is the matrix multiplication of A and B.
#The shape of the new matrix should be (10,25). Using basic numpy math functions only 
#find the sum of all the elements of the new matrix.
#matrix A
A=np.random.random((10,20))
print(A)

[[2.29777671e-01 5.86504129e-01 8.81367426e-01 8.34728993e-01
  2.22817239e-01 9.24851101e-02 4.91674762e-01 7.93227831e-02
  6.16617016e-01 4.00516329e-01 6.94731669e-01 1.40991953e-01
  6.27449768e-01 4.56531831e-01 7.22031685e-01 7.13713777e-01
  9.23900523e-02 4.30898065e-01 1.08622295e-01 3.83818803e-01]
 [3.44737926e-02 5.40982093e-01 7.00002607e-01 1.00088803e-01
  7.06341295e-01 3.73639452e-01 7.07365636e-01 4.89142212e-01
  2.98123516e-01 7.03599581e-01 9.16193927e-01 3.52090646e-01
  1.31677338e-01 1.87615872e-01 8.49475920e-01 1.82075464e-01
  1.20014330e-01 6.75784013e-01 9.67896710e-01 5.34745416e-01]
 [3.44891073e-01 6.28251219e-01 8.38353921e-01 3.49129343e-01
  9.20864915e-01 2.11401470e-01 4.15253086e-02 2.07129524e-01
  9.77553395e-01 4.43476324e-01 7.42236762e-01 1.54665330e-01
  6.48095777e-01 7.00818765e-04 8.37593996e-01 3.48887911e-01
  7.84490785e-01 2.57253244e-01 4.75834908e-01 9.41837345e-01]
 [7.49404489e-01 5.47254479e-01 3.12107352e-01 5.41317623e-01
  1.7

In [90]:
#matrixB
B=np.random.random((20,25))
print(B)

[[5.07070938e-01 8.45915396e-02 4.06002117e-01 9.52012594e-01
  7.05734585e-01 5.86864306e-02 1.84544600e-01 4.55085034e-01
  9.76049314e-01 6.23061191e-01 4.65906942e-01 4.72627695e-01
  3.44377525e-01 1.35170928e-01 2.63723239e-01 4.04486961e-02
  1.39921477e-01 5.49395523e-02 9.35390854e-01 7.25534403e-01
  7.09319679e-01 2.70067889e-01 9.45816830e-01 2.90354861e-01
  4.43503606e-01]
 [1.99848625e-01 5.85826855e-01 1.53773250e-01 2.16627093e-01
  8.35075018e-01 2.91473960e-01 8.64617760e-01 8.55336540e-01
  9.42572444e-01 1.00581762e-01 5.54114927e-01 5.26372744e-01
  5.20131802e-02 4.78900870e-01 4.22000504e-01 1.45127523e-01
  8.24786192e-01 8.04552621e-01 3.12333480e-01 7.46612247e-01
  9.35859141e-01 6.18851443e-01 6.51994648e-01 3.32854922e-01
  8.27350656e-01]
 [9.17488824e-02 4.39135720e-01 5.04156879e-01 8.74043600e-01
  3.16517272e-01 6.52148538e-02 3.30556374e-01 7.54840164e-01
  6.26851578e-01 3.56692207e-01 7.54377859e-01 8.91568539e-02
  9.92244499e-01 2.46841548e-01 3.

In [91]:
#matrix C
C=np.dot(A,B)
print(C)

[[2.63026564 3.15629204 3.90560974 4.10745417 4.59341612 3.82992511
  4.93571031 4.9337809  5.94644056 4.35117524 3.90304169 4.40346966
  4.00816659 3.85464996 3.96669105 4.25786497 5.02047155 4.73083837
  4.38343979 3.26262914 3.17902952 4.5778759  4.45535851 4.41879149
  3.16310733]
 [3.29292061 3.34007651 4.43891961 4.44467315 4.89971554 4.30149936
  5.33241943 5.44818588 5.8628917  5.35257035 3.63208383 5.74163325
  3.52244513 4.60219018 5.42016711 4.7669027  5.98458077 5.28181301
  5.50179147 4.14262536 4.25341645 5.74286825 4.55672612 4.88237969
  3.4554059 ]
 [3.32173908 3.71019991 4.36887929 4.36385925 5.47085096 4.68051787
  5.70101063 5.82203331 5.94698894 4.68383242 4.56611279 5.76958829
  3.7654731  4.65427941 5.46310268 4.77334971 6.26852231 5.96512342
  4.79934242 4.30167085 4.14652156 5.68673093 4.89657514 5.20079419
  3.91715621]
 [4.17473102 3.07583374 4.77161459 5.51526743 5.32627534 5.69429365
  5.6649797  5.9586516  6.7364259  6.14226583 5.02157702 5.85807073
  4.54

In [92]:
print(C.shape)

(10, 25)


In [93]:
print(C.sum())

1199.7368578323353


In [94]:
#Question4.Create a numpy array A of shape(10,1).Using the basic operations of the numpy array generate an array of
#shape(10,1) such that 
#each element is the following function applied on each element of A.
#f(x)=1 / (1 + exp(-x)) 
#Apply this function to each element of A and print the new array holding the value the function returns
'''
Example:
a=[a1,a2,a3]   
n(new array to be printed )=[ f(a1), f(a2), f(a3)]
'''
A=np.random.rand(10,1)
a=lambda x:(1/(1+np.exp(-x)))
print("New array:",np.array(list(map(a,A))))

New array: [[0.69932912]
 [0.56825401]
 [0.67295187]
 [0.64125998]
 [0.7046594 ]
 [0.56524815]
 [0.52786914]
 [0.63782052]
 [0.60022008]
 [0.66650664]]
