In [1]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sn
import pandas as pd
import numpy as np
%matplotlib inline

In [2]:
from sklearn.datasets import load_digits

In [3]:
digit=load_digits()
x=(digit.data)
y=(digit.target)

In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
x_Std=StandardScaler().fit_transform(x)

In [6]:
x_Std

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [7]:
from sklearn.decomposition import PCA
pca = PCA(n_components=40)

In [8]:
principalComponents = pca.fit_transform(x_Std)

In [9]:
principalDf = pd.DataFrame(data = principalComponents)

In [10]:
principalDf

0         1         2         3         4         5         6   \
0     1.914214 -0.954502 -3.946035  2.028724 -0.267174  0.530326 -1.415322   
1     0.588980  0.924636  3.924755 -1.779851 -0.993433 -0.675652  1.878562   
2     1.302039 -0.317189  3.023332 -2.043376 -2.081153  0.935119 -1.296199   
3    -3.020770 -0.868772 -0.801744 -2.187039 -0.556816  0.727125  0.959764   
4     4.528949 -1.093480  0.973121 -1.419510 -1.715107  1.431593  1.073649   
5    -1.301890 -1.148183 -1.574607 -2.413648 -0.630976  0.740804  1.306800   
6     1.434222 -2.957845  2.831278 -0.076952  0.523031  0.010904  0.983716   
7     0.614240  5.462184  0.658242  0.434429  0.850177 -0.954011 -1.833864   
8    -1.098451 -0.665823 -0.041023 -1.102526 -0.900728  0.755130 -0.966471   
9    -0.537970 -0.777493 -1.568923 -0.759981 -0.121339 -0.600989  0.675189   
10    3.378760 -0.495768 -2.280896  1.429204  0.006572 -0.150582 -0.739174   
11    2.063345  2.016679  1.540476 -4.773151 -2.194263  0.344460  3.084411   
12   -1.937011 -1.815246  2.801368 -0.786548  3.025775 -0.384552 -0.647715   
13   -3.258076  2.149124 -1.615647 -1.798927 -0.745365  1.828824  0.763428   
14    5.458744  0.025133  0.182528 -0.119623 -0.541032  0.104813  1.083116   
15   -3.877037  2.606816  1.858528  5.454026  0.615479  0.988486  3.602246   
16    0.921352 -3.262241  3.401443 -3.227336  1.096493  0.081960 -0.573130   
17    1.415335  1.954479  0.560574 -0.368825 -1.302536 -1.883614 -1.063240   
18   -0.926522  2.253018  1.532929  0.111958 -1.640290  0.261413 -0.069196   
19   -2.370963 -2.931915 -0.381362 -3.232761  2.084194  0.545310 -0.615777   
20    2.001901 -1.319746 -2.570950  0.855347 -0.565535 -1.017707 -0.811999   
21    1.694878  2.075387  0.885989 -4.388595 -1.446107 -0.307274  3.643108   
22   -3.114570 -1.058976  2.451496 -0.547892  0.761751 -0.012652 -1.890061   
23   -1.469418  3.910388 -2.078331 -0.869924  0.203793  0.689533 -0.288167   
24    4.003333 -0.322216  0.587683 -2.740556 -1.513543  0.676060  2.088574   
25   -0.376722  0.525118  1.356041  3.106103  0.926276 -1.029448  1.450071   
26    1.286726 -3.969443  2.542968  0.936671  0.282386  0.352675  1.026762   
27    3.842317  3.478237 -1.569507 -1.675843 -0.274117 -0.345101 -0.150010   
28   -0.166537  0.934111  1.259153 -0.086536 -1.045705  0.362902 -0.877880   
29   -2.014425 -2.376845 -0.707905 -3.515253  1.168347  0.694466  0.206821   
...        ...       ...       ...       ...       ...       ...       ...   
1767  4.958572 -1.159637  0.645671 -1.495315 -1.408072  0.580227  2.222105   
1768  1.009034 -3.325936 -0.584417  0.907492 -0.665937  0.398976 -1.279983   
1769 -0.542840 -0.492983 -3.138879  0.952805  0.732337 -1.169261  1.900083   
1770 -3.314656  1.510568 -0.820052 -1.838159 -1.474753  1.442500  2.178247   
1771  2.128214 -2.822365  3.623385 -1.087841 -0.085813  0.389349  1.443187   
1772 -1.814030  1.197999 -3.113638 -1.063800 -1.806720  0.021172  1.294926   
1773  1.374678 -4.417769  0.544578  0.931146  1.151819 -0.342557  0.125666   
1774  0.762953  0.643399  3.119026 -0.449233 -2.038240 -0.268279 -0.225336   
1775 -0.433045  3.216018  2.011168 -0.229288 -1.509355 -1.166808 -2.852440   
1776 -0.525867 -1.154643 -1.889820  0.953332  0.807082 -1.084716  1.495882   
1777  5.106682 -0.289142  0.341408 -1.773524 -2.469449  1.596730  0.885049   
1778  5.900098 -1.710240  1.858915  0.171253 -4.529245  4.714808  0.440304   
1779  1.597139  4.676427  0.469292 -0.503398 -0.074204 -1.780277 -2.551046   
1780 -5.137834 -0.191049  2.223967  2.046425 -0.885015  3.406912 -0.342170   
1781 -1.416098 -1.031485  1.196076  0.841545 -2.197922  2.483195  0.573307   
1782 -4.272989 -1.355840  3.059714  0.367666  1.045032  0.747247  0.006418   
1783 -3.136887 -1.411700  2.238424 -0.085145  0.779779  0.689976 -1.289872   
1784  1.568544 -0.438603 -1.840596 -0.847230  0.413570 -1.193724  2.474056   
1785  0.058277  1.978137  1.807599  1.282991 -1.856845 -0.847036 -3.167590   
1786 -0.711454  0.253346 -2.934788

In [11]:
pca.explained_variance_ratio_

array([0.12033916, 0.09561054, 0.08444415, 0.06498408, 0.04860155,
       0.0421412 , 0.03942083, 0.03389381, 0.02998221, 0.02932003,
       0.02781805, 0.02577055, 0.02275303, 0.0222718 , 0.02165229,
       0.01914167, 0.01775547, 0.01638069, 0.0159646 , 0.01489191,
       0.01347969, 0.01271931, 0.01165837, 0.01057646, 0.00975316,
       0.00944559, 0.00863012, 0.0083664 , 0.00797687, 0.00746436,
       0.00725573, 0.00691908, 0.00653903, 0.00640781, 0.0059117 ,
       0.00571146, 0.0052351 , 0.00481695, 0.00453373, 0.00421775])

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
principalDf_train,principalDf_test,y_train,y_test = train_test_split(principalDf,y,test_size = 0.3)

In [14]:
model=LogisticRegression()
model.fit(principalDf_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [15]:
pred=model.predict(principalDf_test)
pred

array([5, 9, 3, 3, 4, 1, 5, 1, 3, 4, 0, 2, 2, 8, 5, 0, 5, 5, 8, 1, 0, 5,
       3, 3, 6, 5, 6, 4, 4, 0, 9, 2, 0, 2, 8, 9, 2, 5, 4, 2, 0, 7, 1, 5,
       0, 6, 9, 6, 8, 4, 2, 5, 4, 5, 4, 8, 0, 7, 9, 0, 7, 4, 4, 1, 0, 2,
       7, 2, 8, 2, 9, 1, 0, 0, 8, 0, 7, 6, 9, 6, 2, 4, 1, 2, 7, 6, 1, 7,
       8, 3, 9, 9, 5, 2, 2, 2, 0, 9, 1, 0, 9, 7, 7, 7, 4, 5, 3, 3, 7, 1,
       4, 7, 6, 4, 4, 0, 1, 9, 0, 9, 6, 6, 8, 9, 5, 4, 9, 1, 7, 0, 9, 0,
       0, 4, 5, 1, 4, 8, 1, 4, 6, 7, 5, 7, 1, 3, 7, 5, 9, 9, 2, 9, 4, 7,
       3, 4, 4, 5, 1, 0, 9, 4, 8, 3, 0, 7, 7, 1, 5, 4, 9, 6, 1, 7, 5, 1,
       7, 5, 2, 3, 8, 3, 6, 5, 6, 8, 3, 3, 4, 2, 3, 9, 2, 9, 1, 0, 6, 3,
       0, 0, 9, 2, 1, 9, 0, 7, 9, 3, 8, 3, 1, 9, 3, 8, 4, 6, 4, 2, 4, 0,
       7, 4, 0, 7, 2, 2, 0, 8, 3, 0, 6, 5, 9, 6, 1, 3, 9, 5, 0, 9, 4, 7,
       9, 1, 3, 7, 5, 8, 1, 4, 2, 0, 3, 2, 8, 5, 6, 9, 0, 6, 7, 1, 9, 3,
       5, 1, 9, 6, 0, 4, 8, 1, 0, 3, 8, 0, 2, 8, 0, 7, 2, 6, 5, 0, 7, 7,
       7, 8, 7, 3, 1, 9, 8, 9, 4, 7, 5, 1, 1, 7, 2,

In [16]:
from sklearn import metrics
metrics.accuracy_score(y_test,pred)

0.9592592592592593

In [17]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       1.00      0.98      0.99        65
          1       0.89      0.96      0.93        52
          2       1.00      1.00      1.00        55
          3       0.96      0.92      0.94        51
          4       0.98      0.98      0.98        57
          5       0.96      0.96      0.96        55
          6       1.00      0.95      0.97        57
          7       0.94      0.98      0.96        48
          8       0.90      0.97      0.94        39
          9       0.93      0.89      0.91        61

avg / total       0.96      0.96      0.96       540



In [18]:
from sklearn.metrics import confusion_matrix

In [19]:
confusion_matrix(y_test,pred)

array([[64,  0,  0,  0,  0,  1,  0,  0,  0,  0],
       [ 0, 50,  0,  0,  0,  0,  0,  0,  1,  1],
       [ 0,  0, 55,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0, 47,  0,  1,  0,  0,  2,  0],
       [ 0,  0,  0,  0, 56,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0, 53,  0,  0,  0,  2],
       [ 0,  2,  0,  0,  1,  0, 54,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 47,  0,  1],
       [ 0,  0,  0,  1,  0,  0,  0,  0, 38,  0],
       [ 0,  3,  0,  1,  0,  0,  0,  2,  1, 54]], dtype=int64)